; tfree0.g
; called when tool 0 is freed
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Tue Nov 10 2020 12:02:53 GMT+0100 (Central European Standard Time)

;M98 P"/macros/SELECT/Select_T1" ; OLD BEHAVIOR
